### ISSUE TITLE
Invalid db file

### ISSUE THREAD

**Issue by soerenlemke** [soerenlemke/GoSeeQLite#14]
IDE is complaining because the file is a empty .go file. Can we make changes to another file type for not getting error anmyore?
![image](https://github.com/soerenlemke/GoSeeQLite/assets/61249756/68e01ead-55f9-45f5-8815-6b08e43f3a74)

**Comment by soerenlemke** [comment]
@vyshnav-vinod what do you think about that?

**Comment by vyshnav-vinod** [comment]
@soerenlemke This is just for a test. I couldnt think of any other way to produce a invalid file for the test lol. I guess we can change the filetype to something else? Maybe like .py or something? It wont complain then. Or if you can find any invalid db files, we can use those as well.
