### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by vyshnav-vinod** [soerenlemke/GoSeeQLite#5]
One thing we should keep in mind are the tests. We should try to submit tests as well if any new function or a feature is added.

**Comment by soerenlemke** [comment]
You're right! Will add them 👍🏻

**Comment by vyshnav-vinod** [comment]
I can work on the tests. I will open a PR soon

**Comment by soerenlemke** [comment]
I just added basic structure for the database tests. Merging it right now.

**Comment by vyshnav-vinod** [comment]
@soerenlemke it would be better to split the tests right? Like first lets rename every file inside the database folder -> Just remove the `database_` from their names (database_setup.go will change to setup.go). I believe since they are already inside the database folder, the additonal database_  prefix is unnecessary. Then we can split the tests into setup_test.go, connection_test.go and so on. I believe this is the best practice for Go as well.

**Comment by vyshnav-vinod** [comment]
@soerenlemke #7 This was what i was talking about. If its looks good, i can work on the tests using that format.

**Comment by soerenlemke** [comment]
Looking good! Just merged it :)

**Comment by vyshnav-vinod** [comment]
@soerenlemke For the get tables and table columns, what would be the failing tests? If the db file is invalid it would be already caught by NewDatabase, so we cant give a invalid file to that. So should i just add tests for valid db files?

**Comment by soerenlemke** [comment]
Thats right, so lets only do the tests for valid db files.

**Comment by vyshnav-vinod** [comment]
Will do later today when i get time 😄

**Comment by soerenlemke** [comment]
No stress :)

**Comment by soerenlemke** [comment]
Basic tests are implemented. Should we close the issue @vyshnav-vinod ?

**Comment by vyshnav-vinod** [comment]
Yes we can close this @soerenlemke
